spring:
  config:
    activate:
      on-profile: "qa"

build:
  info: "2.31.42"

loans:
  message: "Welcome to Eazybank loans related qa APIs"
  contactDetails:
    name: "Franky"
    email: "franky@shipwright.com"
  onCallSupport:
    - (123)456789
    - (987)654321